#!/bin/bash

set -e
docker ps > /dev/null

if [ "$(docker ps -a | grep pwngun)" ]
then
    docker exec -it pwngun /bin/zsh
else
    docker run -v ~/ctf:/osx -w /osx --env LANG=C.UTF-8 --env LC_ALL=C.UTF-8 --security-opt seccomp=unconfined --privileged --name pwngun -it --rm -h fl3x fl3x3dd/pwngun:latest /bin/zsh
fi
